config:
  validation: true
  warningsAsErrors: false
  checkExhaustiveness: false

complexity:
  LargeClass:
    excludes: &testFolders
      - '**/test/**'
      - '**/commonTest/**'
      - '**/jvmTest/**'
      - '**/jsTest/**'
      - '**/iosTest/**'
  LongMethod:
    excludes: *testFolders

coroutines:
  InjectDispatcher:
    excludes: *testFolders

empty-blocks:
  EmptyFunctionBlock:
    excludes: *testFolders

comments:
    UndocumentedPublicProperty:
      active: true
      excludes: [ '**/test/**', '**/commonTest/**', '**/jvmTest/**', '**/generated-sources/**' ]
      searchProtectedProperty: false
      ignoreEnumEntries: true
