config:
  validation: true
  warningsAsErrors: false
  checkExhaustiveness: false

complexity:
  LargeClass:
    excludes: &testFolders
      - '**/test/**'
      - '**/commonTest/**'
      - '**/jvmTest/**'
      - '**/jsTest/**'
      - '**/iosTest/**'
  LongMethod:
    excludes: *testFolders

coroutines:
  InjectDispatcher:
    excludes: *testFolders

empty-blocks:
  EmptyFunctionBlock:
    excludes: *testFolders

comments:
    UndocumentedPublicClass:
      active: true
      excludes: &testAndGeneratedFolders
        - '**/test/**'
        - '**/commonTest/**'
        - '**/jvmTest/**'
        - '**/jsTest/**'
        - '**/iosTest/**'
        - '**/generated-sources/**'
      ignoreDefaultCompanionObject: true
    UndocumentedPublicFunction:
      active: true
      excludes: *testAndGeneratedFolders
    UndocumentedPublicProperty:
      active: true
      excludes: *testAndGeneratedFolders
      searchProtectedProperty: false
      ignoreEnumEntries: true
