config:
  validation: true
  warningsAsErrors: false
  checkExhaustiveness: false

complexity:
  LargeClass:
    excludes: &testFolders
      - '**/test/**'
      - '**/commonTest/**'
      - '**/jvmTest/**'
      - '**/jsTest/**'
      - '**/iosTest/**'
  LongMethod:
    excludes: *testFolders

coroutines:
  InjectDispatcher:
    excludes: *testFolders

empty-blocks:
  EmptyFunctionBlock:
    excludes: *testFolders

comments:
    UndocumentedPublicClass:
      active: true
      excludes: [ *testFolders, '**/generated-sources/**' ]
      ignoreDefaultCompanionObject: true
    UndocumentedPublicFunction:
      active: true
      excludes: [ *testFolders, '**/generated-sources/**' ]
    UndocumentedPublicProperty:
      active: true
      excludes: [ *testFolders, '**/generated-sources/**' ]
      searchProtectedProperty: false
      ignoreEnumEntries: true
