name: Validate PR

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  validate-pr:
    runs-on: macos-latest
    name: Validate PR
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Clean Build with Gradle
        run: ./gradlew clean build

      - name: Publish Build to MavenLocal  # used by the samples
        run: ./gradlew publishToMavenLocal

      - name: Build Kotlin-MCP-Client Sample
        working-directory: ./samples/kotlin-mcp-client
        run: ./gradlew clean build

      - name: Build Kotlin-MCP-Server Sample
        working-directory: ./samples/kotlin-mcp-server
        run: ./gradlew clean build

      - name: Build Weather-Stdio-Server Sample
        working-directory: ./samples/kotlin-mcp-client
        run: ./gradlew clean build

      - name: Disable Auto-Merge on Fail
        if: failure()
        run: gh pr merge --disable-auto "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
