name: Validate PR

on:
  workflow_dispatch:
  pull_request:
    types: [auto_merge_enabled]

jobs:
  validate-pr:
    runs-on: macos-latest
    name: Validate PR
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Clean Build with Gradle
        run: ./gradlew clean build

      - name: Disable Auto-Merge on Fail
        if: failure()
        run: gh pr merge --disable-auto "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
